### ISSUE TITLE
stopped working today

### ISSUE THREAD

**Issue by kousha789123** [AnchitSingh/TwitterAdBlocker#1]
Hi,
this was working until today. I appreciate if you take a min and fix it please. Thanks. I loved it

**Comment by AnchitSingh** [comment]
![Screenshot from 2024-07-31 15-44-59](https://github.com/user-attachments/assets/6d6dac51-62e6-4561-b095-51e314dcffcf)
I tested the code on multiple browsers and on incognito tab too and the code is working fine. Twitter has not updated the Ads layout structure in my region. If you are seeing the ads make sure the extension you are using to run the code is working fine. Also make sure you are using the latest code from this repo. Try clearing the browser cache.
The extension I use to run the code is ["User Javascript and CSS"](https://chromewebstore.google.com/detail/user-javascript-and-css/nbhcbdghjpllgmfilhnhkllmkecfmpld?hl=en&pli=1)

**Comment by kousha789123** [comment]
You are right. It still works on Chrome, but not on Safari. It used to work for both; I used this https://getsprinkles.app 
So it is possible that only for Safari they have made some changes to css for ads.

**Comment by kousha789123** [comment]
here is my contribution to one that works on Safari https://github.com/kouroshshafi/AdBlock-Twitter/tree/main

Thanks again and yours is still great for Chrome.
